name: CI (integration tests)

# We only run the integration tests with Bors. There is a specific reason for
# this. Using Bors makes it easier for us to limit the total number of
# concurrent jobs. This is important because it keeps us from triggering 
# GitHub's abuse rate limits.

on:
  push:
    branches:
      - master
      - staging
      - trying
    tags: '*'
jobs:
  integration:
    if: github.event_name == 'push'
    name: Integration/Julia ${{ matrix.version }}/${{ matrix.os }}/${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        arch:
          - x64
        os:
          - ubuntu-latest
        version:
          - '1.3'
          - '1'
          - 'nightly'
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - run: git config --global user.email "noreply@example.com"
      - run: git config --global user.name "GitHub Actions"
      - uses: julia-actions/julia-runtest@v1
        env:
          AUTOMERGE_RUN_INTEGRATION_TESTS: "true"
          AUTOMERGE_INTEGRATION_TEST_REPO: "bcbi-test/automerge-integration-test-repo"
          BCBI_TEST_USER_GITHUB_TOKEN: ${{ secrets.BCBI_TEST_USER_GITHUB_TOKEN }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
