name: GITHUB_EVENT_PATH

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.2.0]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        run: julia --project -e 'using Pkg; Pkg.instantiate()'
      - name: Print file content
        run: julia --project -e 'using JSON; c = JSON.parsefile(ENV["GITHUB_EVENT_PATH"]); show(stdout, "text/plain", c)'
